### ISSUE TITLE
Create a unified artifact type hierarchy?

### ISSUE THREAD

**Issue by mbrush** [data2health/contribution-data-model#15]
We had previously decided that, for our initial release, we do not attempt to provide a formally unified model/hierarchy of artifact types that re-uses/aligns/maps terms from existing terminologies in this space into a logically consistent and cross-referenced structure.  Rather, we provide an informal recommended value set types (possible with mappings to a couple established terminologies).

On the 8-15-19 Arch Attribution call, Kristi seemed convinced that a unified model/hierarchy of terms/concepts here would be very valuable product of our work, and greatly enhance the value of our modeling framework. Others concurred about the value of this product, but raised concerns about the feasibility of providing this by the September v1 release target.

We should discuss the utility of such a deliverable (what value does it provide, for who/what use cases), and how to approach this in the short term (for the September v1 release) vs longer term (December, beyond).

Nicole, Lisa, and Kristi are working to assemble an overview of existing terminologies and efforts at unification/alignment that can help us make decisions here, and weight trade off of effort required vs value added (see #14)

**Comment by kristiholmes** [comment]
Thanks, Matt.  I do think that this work is of value to incentivize the end users, although as I mentioned on the call, I remain agnostic about whether it is done now and whether this work is completed in the context of the Architecting Attribution effort through CD2H. Perhaps we can outline some best examples that can be used in a more machine operable manner.

**Comment by mellybelly** [comment]
I think this is out of scope for the pending ontology, model release, and the manuscript. I agree that the utility/requirements for end users should be determined, as well as how current sources fail to meet those needs. Probably one could use WikiData and add any additional sources there as needed?
